version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore(security): '
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore(security): '
    # Disable version updates for docker dependencies
    open-pull-requests-limit: 0

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore(security): '
    # Disable version updates for GitHub Actions dependencies
    open-pull-requests-limit: 0
