version: "3.8"

services:
  cms:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cms
    env_file:
      - .env
    expose:
      - "1337"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./.tmp:/app/.tmp
    restart: unless-stopped

  frontend:
    # add your frontend application here
    image: node:22-alpine # Replace with your actual frontend image
    container_name: frontend
    command: ["sh", "-c", "while :; do sleep 10; done"] # Placeholder, replace with your frontend start command
    depends_on:
      - cms
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - frontend
      - cms
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
