name: Bug report
description: Create a report to help us improve
labels:
  - bug
assignees:
  - this-oliver
body:
  - type: input
    id: problem
    attributes:
      label: What is the problem?
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    id: device
    attributes:
      label: Device
      description: e.g. desktop, mobile
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: Browser
      description: e.g. chrome, safari
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
